#!/usr/bin/env node
/**
 * One-command setup.
 *
 *   cp .env.setup.example .env.setup   # fill in seven values
 *   npm run setup
 *
 * Links the Supabase project, applies migrations, generates VAPID keys and a
 * cron secret, deploys the edge function, creates the single user account,
 * finds the Telegram chat ID, wires the schedule, and sends a test
 * notification to the phone.
 *
 * Safe to re-run. Every step is idempotent: keys are reused once generated,
 * the user is created only if absent, and the channel row is upserted.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, chmodSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { webcrypto as crypto } from 'node:crypto';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SETUP_ENV = join(root, '.env.setup');
const GENERATED = join(root, '.env.generated');
const LOCAL_ENV = join(root, '.env.local');

/* ------------------------------------------------------------------ output */

const step = (n, msg) => console.log(`\n[${n}] ${msg}`);
const ok = (msg) => console.log(`    ok   ${msg}`);
const note = (msg) => console.log(`    --   ${msg}`);

function die(msg, hint) {
  console.error(`\nSetup stopped: ${msg}`);
  if (hint) console.error(`\n${hint}`);
  process.exit(1);
}

/* -------------------------------------------------------------------- env  */

function parseEnv(path) {
  if (!existsSync(path)) return {};
  const out = {};
  for (const raw of readFileSync(path, 'utf8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

/*
 * What every deployment needs, whoever ends up using it.
 *
 * This is the environment: a project, a schema, secrets, functions and a
 * schedule. Nothing here is about a particular person.
 */
const REQUIRED = [
  'SUPABASE_PROJECT_REF',
  'SUPABASE_DB_PASSWORD',
  'SUPABASE_ANON_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_ACCESS_TOKEN',
];

/*
 * The personal half, which is optional on purpose.
 *
 * While this serves one person it is convenient for setup to also create that
 * account and wire up their Telegram — so those steps still run, exactly as
 * before, when the values are present.
 *
 * When it serves many, they are simply absent from .env.setup and every step
 * below skips itself. That is the whole migration: two lines removed from a
 * config file, no code touched, no script rewritten. Accounts arrive through
 * sign-up and configure their own notifications in Settings, both of which
 * already exist.
 */
const PERSONAL = ['APP_EMAIL', 'APP_PASSWORD', 'TELEGRAM_BOT_TOKEN'];

if (!existsSync(SETUP_ENV)) {
  die(
    '.env.setup does not exist.',
    'Run:\n  cp .env.setup.example .env.setup\n\nThen fill in the values it asks for and run this again.',
  );
}

const cfg = parseEnv(SETUP_ENV);

/** True when this run should also provision a person, not just a project. */
const withAccount = PERSONAL.every((k) => Boolean(cfg[k]));

const missing = REQUIRED.filter((k) => !cfg[k]);
if (missing.length) {
  die(
    `.env.setup is missing ${missing.length} value${missing.length > 1 ? 's' : ''}.`,
    `Still needed:\n${missing.map((k) => `  ${k}`).join('\n')}`,
  );
}

const REF = cfg.SUPABASE_PROJECT_REF;
const SUPABASE_URL = `https://${REF}.supabase.co`;
const DISPATCH_URL = `${SUPABASE_URL}/functions/v1/dispatch`;

/* --------------------------------------------------- generated secrets ---- */

step(1, 'Generating VAPID keys and a cron secret');

const generated = parseEnv(GENERATED);

/** Web Push needs a stable P-256 keypair. Regenerating it would invalidate
 *  every existing subscription, so it is generated once and reused. */
async function generateVapid() {
  const pair = await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, [
    'sign',
    'verify',
  ]);
  const raw = new Uint8Array(await crypto.subtle.exportKey('raw', pair.publicKey));
  const jwk = await crypto.subtle.exportKey('jwk', pair.privateKey);
  const b64url = (b) => Buffer.from(b).toString('base64url');
  return { publicKey: b64url(raw), privateKey: jwk.d };
}

if (!generated.VAPID_PUBLIC_KEY || !generated.VAPID_PRIVATE_KEY) {
  const v = await generateVapid();
  generated.VAPID_PUBLIC_KEY = v.publicKey;
  generated.VAPID_PRIVATE_KEY = v.privateKey;
  ok('new VAPID keypair');
} else {
  note('reusing existing VAPID keypair (regenerating would break subscriptions)');
}

if (!generated.CRON_SECRET) {
  generated.CRON_SECRET = Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString(
    'base64url',
  );
  ok('new cron secret');
} else {
  note('reusing existing cron secret');
}

writeFileSync(
  GENERATED,
  `# Generated by scripts/setup.mjs. Do not commit. Do not regenerate the VAPID\n` +
    `# keys once a device has subscribed — it would silently break Web Push.\n` +
    Object.entries(generated)
      .map(([k, v]) => `${k}=${v}`)
      .join('\n') +
    '\n',
);
chmodSync(GENERATED, 0o600);
ok('.env.generated written');

/* ------------------------------------------------------------- supabase --- */

const cliEnv = {
  ...process.env,
  SUPABASE_ACCESS_TOKEN: cfg.SUPABASE_ACCESS_TOKEN,
};

function supabase(args, opts = {}) {
  try {
    return execFileSync('npx', ['--yes', 'supabase', ...args], {
      cwd: root,
      env: cliEnv,
      encoding: 'utf8',
      stdio: opts.quiet ? 'pipe' : 'inherit',
    });
  } catch (e) {
    if (opts.allowFail) return null;
    die(
      `\`supabase ${args[0]} ${args[1] ?? ''}\` failed.`,
      e.stdout || e.stderr || String(e.message),
    );
  }
}

step(2, 'Linking the Supabase project');
// Output is inherited rather than captured: if the CLI ever asks something,
// a captured stream would hang with a blank terminal and no way to answer.
supabase(['link', '--project-ref', REF, '--password', cfg.SUPABASE_DB_PASSWORD]);
ok(`linked to ${REF}`);

step(3, 'Applying migrations');
supabase(['db', 'push', '--password', cfg.SUPABASE_DB_PASSWORD]);
ok('schema and schedule applied');

step(4, 'Setting edge function secrets');
supabase(
  [
    'secrets',
    'set',
    `VAPID_PUBLIC_KEY=${generated.VAPID_PUBLIC_KEY}`,
    `VAPID_PRIVATE_KEY=${generated.VAPID_PRIVATE_KEY}`,
    // A contact address is required by the Web Push spec rather than by us.
    // Falls back to a project one so a deployment with no named owner is
    // still spec-compliant.
    `VAPID_SUBJECT=mailto:${cfg.APP_EMAIL || 'noreply@' + REF + '.supabase.co'}`,
    `CRON_SECRET=${generated.CRON_SECRET}`,
    `APP_URL=${cfg.APP_URL || 'http://localhost:5173'}`,
    // Telegram is a per-person channel, so its token is only set when there
    // is a person. Web Push needs nothing here and works for everyone.
    ...(cfg.TELEGRAM_BOT_TOKEN ? [`TELEGRAM_BOT_TOKEN=${cfg.TELEGRAM_BOT_TOKEN}`] : []),
  ],
  { quiet: true },
);
ok('secrets set');

step(5, 'Deploying the edge functions');
supabase(['functions', 'deploy', 'dispatch']);
ok('dispatch deployed');
// parse-food is deployed here too. It was once left out, and the failure was
// invisible in the right way to waste an evening: the app showed "couldn't
// reach the parser", which reads as a network problem, when the function
// simply was not there.
supabase(['functions', 'deploy', 'parse-food']);
ok('parse-food deployed');
supabase(['functions', 'deploy', 'assist']);
ok('assist deployed');
supabase(['functions', 'deploy', 'calendar']);
ok('calendar deployed');

/* ------------------------------------------------------------- rest api --- */

const admin = {
  async call(path, init = {}) {
    const res = await fetch(`${SUPABASE_URL}${path}`, {
      ...init,
      headers: {
        apikey: cfg.SUPABASE_SERVICE_ROLE_KEY,
        Authorization: `Bearer ${cfg.SUPABASE_SERVICE_ROLE_KEY}`,
        'Content-Type': 'application/json',
        ...(init.headers ?? {}),
      },
    });
    const text = await res.text();
    const body = text ? JSON.parse(text) : null;
    if (!res.ok) throw new Error(`${path} -> HTTP ${res.status}: ${text.slice(0, 300)}`);
    return body;
  },
};

/* ---------------------------------------------------------- the person ---
 *
 * Steps 6 to 8 provision an account and its notification channel. They run
 * only when .env.setup names one, and are skipped entirely otherwise — a
 * deployment serving many people gets its accounts from sign-up, and each
 * configures notifications from Settings.
 *
 * Both of those paths already exist, so removing APP_EMAIL, APP_PASSWORD and
 * TELEGRAM_BOT_TOKEN from the config is the entire difference between a
 * personal install and a shared one.
 * ---------------------------------------------------------------------- */

let userId = null;

if (!withAccount) {
  note('no APP_EMAIL in .env.setup, so no account was created — sign up in the app');
} else {
  step(6, 'Creating your account');

  let userId;
  const existing = await admin.call(
    `/auth/v1/admin/users?filter=${encodeURIComponent(cfg.APP_EMAIL)}`,
  );
  const found = (existing?.users ?? []).find((u) => u.email === cfg.APP_EMAIL);

  if (found) {
    userId = found.id;
    note(`account already exists for ${cfg.APP_EMAIL}`);
  } else {
    const created = await admin.call('/auth/v1/admin/users', {
      method: 'POST',
      body: JSON.stringify({
        email: cfg.APP_EMAIL,
        password: cfg.APP_PASSWORD,
        email_confirm: true,
      }),
    });
    userId = created.id;
    ok(`account created for ${cfg.APP_EMAIL}, already confirmed`);
  }

  /* ------------------------------------------------------------- telegram --- */

  step(7, 'Finding your Telegram chat');

  const updates = await fetch(
    `https://api.telegram.org/bot${cfg.TELEGRAM_BOT_TOKEN}/getUpdates`,
  ).then((r) => r.json());

  if (!updates.ok) {
    die(
      `Telegram rejected the bot token: ${updates.description ?? 'unknown error'}`,
      'Check TELEGRAM_BOT_TOKEN in .env.setup against what @BotFather sent you.',
    );
  }

  const chat = updates.result
    ?.map((u) => u.message?.chat ?? u.edited_message?.chat)
    .filter(Boolean)
    .pop();

  if (!chat) {
    die(
      'Telegram has no messages from you, so there is no chat ID to find.',
      'Open Telegram, find the bot you just created, send it any message\n' +
        '(literally "hi" is fine), then run `npm run setup` again.\n\n' +
        'Everything up to this point is already done, so the re-run is quick.',
    );
  }

  ok(`chat found: ${chat.first_name ?? chat.title ?? chat.id}`);

  /* ------------------------------------------------------- wire it together - */

  step(8, 'Configuring the delivery channel and schedule');

  const channels = await admin.call(
    `/rest/v1/notification_channels?user_id=eq.${userId}&kind=eq.telegram&select=id`,
  );

  if (channels.length) {
    await admin.call(`/rest/v1/notification_channels?id=eq.${channels[0].id}`, {
      method: 'PATCH',
      body: JSON.stringify({
        config: { chat_id: String(chat.id) },
        enabled: true,
        failed_at: null,
        failure_reason: null,
        priority: 10,
      }),
    });
    note('existing Telegram channel updated');
  } else {
    await admin.call('/rest/v1/notification_channels', {
      method: 'POST',
      body: JSON.stringify({
        user_id: userId,
        kind: 'telegram',
        config: { chat_id: String(chat.id) },
        priority: 10,
      }),
    });
    ok('Telegram channel created at priority 10');
  }

  await admin.call('/rest/v1/rpc/setup_dispatch', {
    method: 'POST',
    body: JSON.stringify({ p_url: DISPATCH_URL, p_secret: generated.CRON_SECRET }),
  });
  ok('scheduler pointed at the dispatch function');

  /* --------------------------------------------------------------- frontend - */
}

step(9, 'Writing .env.local for the app');

writeFileSync(
  LOCAL_ENV,
  [
    '# Generated by scripts/setup.mjs. Do not commit.',
    '# These two values are public by design: the anon key grants access to',
    '# nothing on its own, because RLS is what protects the data.',
    `VITE_SUPABASE_URL=${SUPABASE_URL}`,
    `VITE_SUPABASE_ANON_KEY=${cfg.SUPABASE_ANON_KEY}`,
    `VITE_VAPID_PUBLIC_KEY=${generated.VAPID_PUBLIC_KEY}`,
    '',
  ].join('\n'),
);
chmodSync(LOCAL_ENV, 0o600);
ok('.env.local written');

/* ------------------------------------------------------------------ prove - */

if (!withAccount) {
  ok('environment ready. Create an account in the app to start using it.');
} else {
  step(10, 'Sending a test notification to your phone');

  const res = await fetch(DISPATCH_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-cron-secret': generated.CRON_SECRET },
    body: JSON.stringify({}),
  });
  const body = await res.text();

  if (!res.ok) {
    die(`the dispatch function returned HTTP ${res.status}`, body.slice(0, 600));
  }

  note('scheduled run executed:');
  console.log(
    body
      .split('\n')
      .map((l) => `       ${l}`)
      .join('\n'),
  );

  console.log(`
  -------------------------------------------------------------------------------
  Setup finished.

  The scheduled run above will report "too-early" unless you happen to be inside
  the 07:00 window. That is correct behaviour, not a failure: it proves the cron
  path executes and the digest logic is making a real decision.

  To prove delivery end to end right now, send yourself a test:

    npm run test:notify

  Check your phone. If a Telegram message arrives, the whole pipeline works and
  Phase 0's hard requirement is met.

  Then start the app:

    npm run dev
  -------------------------------------------------------------------------------
  `);
}
